### ISSUE TITLE
Documentation does not build

### ISSUE THREAD

**Issue by manufactory** [posit-dev/great-tables#507]
## Prework

- [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) and [contributing guidelines](https://github.com/posit-dev/great_tables/blob/main/.github/CONTRIBUTING.md).
- [x] If there is [already a relevant issue](https://github.com/posit-dev/great_tables/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

Describe the bug clearly and concisely.

## Reproducible example

- [x] Post a minimal reproducible example (MRE) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
  - [x] **Runnable**: post enough code and data so any onlooker can create the error on their own computer.
  - [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
  - [x] **Readable**: format your code according to the [Style Guide for Python Code](https://peps.python.org/pep-0008/).

- `make docs-build` fails.
- This worked just fine with 0.13.0
```
    python -m build --wheel --skip-dependency-check --no-isolation

    python -m installer --destdir=tmp_install dist/*.whl
    PYTHONPATH="${PWD}/tmp_install//usr/lib/python3.12/site-packages" make docs-build
```
gives 
```
ERROR: NotFound: No such file or directory (os error 2): readfile '/home/manuel/src/aur/python-great-tables/src/python-great-tables-0.14.0/docs/a-latex_examples/index.log'
Path: /home/manuel/src/aur/python-great-tables/src/python-great-tables-0.14.0/docs/a-latex_examples/index.log

Stack trace:
Path: /home/manuel/src/aur/python-great-tables/src/python-great-tables-0.14.0/docs/a-latex_examples/index.log
    at readTextFileSync (ext:deno_fs/30_fs.js:859:10)
    at Object.Deno.readTextFileSync (file:///opt/quarto/bin/quarto.js:5047:25)
    at initialCompileLatex (file:///opt/quarto/bin/quarto.js:77172:18)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async generatePdf (file:///opt/quarto/bin/quarto.js:77118:22)
    at async Object.complete (file:///opt/quarto/bin/quarto.js:77398:27)
    at async file:///opt/quarto/bin/quarto.js:70765:31
    at async withTimingAsync (file:///opt/quarto/bin/quarto.js:19479:25)
    at async Object.complete (file:///opt/quarto/bin/quarto.js:70763:13)
    at async Object.onPostProcess (file:///opt/quarto/bin/quarto.js:78273:36)
make: *** [Makefile:45: docs-build] Error 1

```

## Expected result

Docs build

## Development environment

- Operating System: Arch Linux
- **great_tables** Version: 0.14.0

## Additional context

- Deleting `docs/a-latex_examples` fixes the issue and the docs build as expected

**Comment by machow** [comment]
I wonder if this could be related to quarto needing a latex install, or something similar? We regenerate the docs every CI run, and it seems to work okay, so I'm a bit puzzled by what might be causing this error :/
